WebApplication2/Models/Project.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace WebApplication2.Models
{
    public class Project
    {
        public string Id { get; set; }
        public string Name { get; set; }
        [DisplayName ("Repository Link")]
        public string RepositoryLink { get; set; }
        public string Language { get; set; }

    }
}

WebApplication2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Caching;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Let's have a chat.";

            return View();
        }

    }
}

WebApplication2/Controllers/LanguagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class LanguagesController : Controller
    {
        // GET: Languages
        
        public ActionResult Index()
        {
            ViewBag.Message = "Languages are the spice of life!";

            return View();
        }

        [Route("Languages/Ruby")]
        public ActionResult Ruby()
        {
            ViewBag.Message = "Ruby is the language of the people!";

            return View();
        }

        [Route("Languages/C#")]
        public ActionResult CSharp()
        {
            ViewBag.Message = "C Sharp can be tricky.";

            return View();
        }

        [Route("Languages/Javascript")]
        public ActionResult Javascript()
        {
            ViewBag.Message = "Build powerful games with Javascript.";

            return View();
        }
    }
}

WebApplication2/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Caching;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class ProjectController : Controller
    {
        ObjectCache cache = MemoryCache.Default;
        List<Project> projects;

        public ProjectController()
        {
            projects = cache["projects"] as List<Project>;
            if (projects == null)
            {
                projects = new List<Project>();
            }
        }

        public void SaveCache()
        {
            cache["projects"] = projects;
        }

        // GET: Project
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ViewProject(string id)
        {
            Project project = projects.FirstOrDefault(c => c.Id == id);
            if(project == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(project);
            }

            
        }

        public ActionResult AddProject()
        {

            return View();
        }

        [HttpPost]
        public ActionResult AddProject(Project project)
        {
            project.Id = Guid.NewGuid().ToString();
            projects.Add(project);
            SaveCache();

            return RedirectToAction("ProjectList");
        }

        public ActionResult EditProject(string id)
        {
            Project project = projects.FirstOrDefault(c => c.Id == id);
            if (project == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(project);
            }

        }

        [HttpPost]
        public ActionResult EditProject(Project project, string id)
        {
            var projectToEdit = projects.FirstOrDefault(c => c.Id == id);

            if (project == null)
            {
                return HttpNotFound();
            }
            else
            {
                projectToEdit.Name = project.Name;
                projectToEdit.RepositoryLink = project.RepositoryLink;
                projectToEdit.Language = project.Language;
                SaveCache();

                return RedirectToAction("ProjectList");
            }
        }

        public ActionResult DeleteProject(string id)
        {
            Project project = projects.FirstOrDefault(c => c.Id == id);
            if (project == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(project);
            }
        }

        [HttpPost]
        [ActionName("DeleteProject")]
        public ActionResult ConfirmDeleteProject(string id)
        {
            Project project = projects.FirstOrDefault(c => c.Id == id);
            if (project == null)
            {
                return HttpNotFound();
            }
            else
            {
                projects.Remove(project);
                return RedirectToAction("ProjectList");
            }
        }

        public ActionResult ProjectList()
        {
             return View(projects);
        }
    }


}

WebApplication2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebApplication2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApplication2/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<link rel="stylesheet" href="~/Content/index.css" />

<div class="jumbotron">
    <div class="jumbo-text">
        <h1>Sparta Global Portfolio</h1>
        <p class="lead">At Sparta, you can learn a variety of programming languages and coding methodologies. By the end of the 13 weeks intensive training, you will be equipped with the skills necessary to launch your career as a programmer! </p>
        <button class="btn btn-primary btn-lg custom-button">@Html.ActionLink("Learn more", "Index", "Project")</button>
    </div>
</div>

<div class="row">
    <div class="col-md-4 text-center">
        <h2>Project 1</h2>
        <p>
            Solo Web-based Game project.
        </p>
        <p><a class="btn btn-primary" href="#">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4 text-center">
        <h2>Project 2</h2>
        <p>
            Full Stack Web-development project.
        </p>
        <p><a class="btn btn-primary" href="#">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4 text-center">
        <h2>Project 3</h2>
        <p>
            Unit, Intergration and Automation Testing Project.
        </p>
        <p><a class="btn btn-primary" href="#">Learn more &raquo;</a></p>
    </div>
</div>

WebApplication2/Views/Languages/CSharp.cshtml
@{
    ViewBag.Title = "CSharp";
}


<link rel="stylesheet" href="~/Content/Javascript.css" />

<h2>C#</h2>

<div class="container">

    <hr class="featurette-divider">

    <!-- First Featurette -->
    <div class="featurette" id="about">
        <img class="featurette-image img-circle img-responsive pull-right" src="~/Content/Images/js.gif">
        <h2 class="featurette-heading">
            What you should know
            <span class="text-muted">about C#</span>
        </h2>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
    </div>

    <hr class="featurette-divider">

    <!-- Second Featurette -->
    <div class="featurette" id="services">
        <img class="featurette-image img-rounded img-responsive pull-left" src="~/Content/Images/A.jpg">
        <h2 class="featurette-heading">
            C# is a very
            <span class="text-muted">popular language.</span>
        </h2>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
    </div>

    <hr class="featurette-divider">

    <!-- Third Featurette -->
    <div class="featurette" id="contact">
        <img class="featurette-image img-circle img-responsive pull-right" src="~/Content/Images/frameworks-js-1.jpg">
        <h2 class="featurette-heading">
            C# has many
            <span class="text-muted">frameworks to make it easy.</span>
        </h2>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
    </div>

    <hr class="featurette-divider">
</div>

WebApplication2/Views/Languages/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<link rel="stylesheet" href="~/Content/LanguagesIndex.css" />

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Learn the Lingo
            <small>We are multilingual.</small>
        </h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint, explicabo dolores ipsam aliquam inventore corrupti eveniet quisquam quod totam laudantium repudiandae obcaecati ea consectetur debitis velit facere nisi expedita vel?</p>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Languages</h2>
    </div>
    <div class="col-lg-4 col-sm-6 text-center">
        <img class="img-circle img-responsive img-center" src="~/Content/Images/Logo_javascript.png" alt="">
        <h3>
            Javascript
       
        </h3>
        <p>Javascript is the language of functionality. Learn how it could change your life.</p>
        <button class="btn btn-primary custom-button">@Html.ActionLink("Learn more", "Javascript", "Languages") </button>
    </div>
    <div class="col-lg-4 col-sm-6 text-center">
        <img class="img-circle img-responsive img-center" src="~/Content/Images/Logo_ruby.png" alt="">
        <h3>
            Ruby
            
        </h3>
        <p>Ruby is a human friendly language so if you speak human, you're already half way to knowing Ruby.</p>
        <button class="btn btn-primary custom-button">@Html.ActionLink("Learn more", "Ruby", "Languages") </button>
    </div>
    <div class="col-lg-4 col-sm-6 text-center">
        <img class="img-circle img-responsive img-center" src="~/Content/Images/Logo_csharp.png" alt="">
        <h3>
            C#
            
        </h3>
        <p>When you first start learning C# you'll be more on the blunt side than the sharp side, but that's okay.</p>
        <button class="btn btn-primary custom-button">@Html.ActionLink("Learn more", "CSharp", "Languages") </button>
    </div>
</div>

WebApplication2/Views/Languages/Javascript.cshtml
@{
    ViewBag.Title = "Javascript";
}

<link rel="stylesheet" href="~/Content/Javascript.css" />

<h2>Javascript</h2>

<div class="container">

    <hr class="featurette-divider">

    <!-- First Featurette -->
    <div class="featurette" id="about">
        <img class="featurette-image img-circle img-responsive pull-right" src="~/Content/Images/js.gif">
        <h2 class="featurette-heading">
            What you should know
            <span class="text-muted">about Javascript</span>
        </h2>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
    </div>

    <hr class="featurette-divider">

    <!-- Second Featurette -->
    <div class="featurette" id="services">
        <img class="featurette-image img-rounded img-responsive pull-left" src="~/Content/Images/A.jpg">
        <h2 class="featurette-heading">
            Javascript is a very
            <span class="text-muted">popular language.</span>
        </h2>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
    </div>

    <hr class="featurette-divider">

    <!-- Third Featurette -->
    <div class="featurette" id="contact">
        <img class="featurette-image img-circle img-responsive pull-right" src="~/Content/Images/frameworks-js-1.jpg">
        <h2 class="featurette-heading">
            Javascript has many
            <span class="text-muted">frameworks to make it easy.</span>
        </h2>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
    </div>

    <hr class="featurette-divider">

WebApplication2/Views/Languages/Ruby.cshtml
@{
                /**/

                ViewBag.Title = "Ruby";
}

<link rel="stylesheet" href="~/Content/Javascript.css" />
<h2>Ruby</h2>

<div class="container">

    <hr class="featurette-divider">

    <!-- First Featurette -->
    <div class="featurette" id="about">
        <img class="featurette-image img-circle img-responsive pull-right" src="~/Content/Images/js.gif">
        <h2 class="featurette-heading">
            What you should know
            <span class="text-muted">about Ruby</span>
        </h2>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
    </div>

    <hr class="featurette-divider">

    <!-- Second Featurette -->
    <div class="featurette" id="services">
        <img class="featurette-image img-rounded img-responsive pull-left" src="~/Content/Images/A.jpg">
        <h2 class="featurette-heading">
            Ruby is a very
            <span class="text-muted">friendly language.</span>
        </h2>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
    </div>

    <hr class="featurette-divider">

    <!-- Third Featurette -->
    <div class="featurette" id="contact">
        <img class="featurette-image img-circle img-responsive pull-right" src="~/Content/Images/frameworks-js-1.jpg">
        <h2 class="featurette-heading">
            Ruby has powerful
            <span class="text-muted">frameworks to make it easy.</span>
        </h2>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
    </div>

    <hr class="featurette-divider">

WebApplication2/Views/Project/AddProject.cshtml
@model WebApplication2.Models.Project

@{
    ViewBag.Title = "Add Project";
}

<h2>Add Project</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Project</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RepositoryLink, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.EditorFor(model => model.RepositoryLink, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RepositoryLink, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Language, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Language, new SelectList(
                                  new List<Object>{
                                       new { value = 0 , text = "Javascript"  },
                                       new { value = 1 , text = "Ruby" },
                                       new { value = 2 , text = "C#"}
                                    },
                                  "value",
                                  "text",
                                   2), htmlAttributes: new { @class = "form-control" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplication2/Views/Project/DeleteProject.cshtml
@model WebApplication2.Models.Project

@{
    ViewBag.Title = "Delete Project";
}

<h2>Delete Project</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RepositoryLink)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RepositoryLink)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Language)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Language)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication2/Views/Project/EditProject.cshtml
@model WebApplication2.Models.Project

@{
    ViewBag.Title = "EditProject";
}

<h2>EditProject</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Project</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RepositoryLink, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RepositoryLink, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RepositoryLink, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Language, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Language, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Language, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplication2/Views/Project/Index.cshtml
@{
    ViewBag.Title = "Projects Index";
}

<link rel="stylesheet" href="~/Content/ProjectIndex.css"/>

<h2>Projects Index</h2>

<div class="image-container">
    <div class="row text-center">
        <div class="col-md-4">
            <img class="image img-circle img-responsive img-thumbnail" src="~/Content/Images/gamepad.png"/>
            <h5>Solo Web-based Game project.</h5>
        </div>
        <div class="col-md-4">
            <img class="image img-circle img-responsive img-thumbnail" src="~/Content/Images/webdev.png" />
            <h5>Solo Web-based Game project.</h5>
        </div>    
        <div class="col-md-4">
            <img class="image img-circle img-responsive img-thumbnail" src="~/Content/Images/testing.png" />
            <h5>Solo Web-based Game project.</h5>
        </div>    
    </div>
</div>


<p>@Html.ActionLink("View Full Project List", "ProjectList", "Project")</p>

WebApplication2/Views/Project/ProjectList.cshtml
@model IEnumerable<WebApplication2.Models.Project>

@{
    ViewBag.Title = "Project List";
}

<h2>Project List</h2>

<p>
    @Html.ActionLink("Create New", "AddProject") 
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RepositoryLink)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Language)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RepositoryLink)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Language)
        </td>
        <td>
            @Html.ActionLink("Edit", "EditProject", new { id=item.Id }) |
            @Html.ActionLink("Details", "ViewProject", new { id=item.Id }) |
            @Html.ActionLink("Delete", "DeleteProject", new { id=item.Id })
        </td>
    </tr>
}

</table>

WebApplication2/Views/Project/ViewProject.cshtml
@model WebApplication2.Models.Project

@{
    ViewBag.Title = "View Project";
}

<h2>View Project</h2>

<div>
    <h4>Project</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RepositoryLink)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RepositoryLink)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Language)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Language)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "EditProject", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "ProjectList")
</p>

WebApplication2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Sparta Global Profile", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Languages", "Index", "Languages")</li>
                    <li>@Html.ActionLink("Projects", "Index", "Project")</li>
                </ul> 
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>